#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
APACHE_CONF="/etc/httpd/conf.d/schoolwire.conf"
SERVICE_FILE="/etc/systemd/system/schoolwire.service"
RUN_USER="$(id -un)"
RUN_GROUP="$(id -gn)"

if [[ ${EUID:-$(id -u)} -eq 0 ]]; then
  SUDO=""
else
  if ! command -v sudo >/dev/null 2>&1; then
    echo "This script needs sudo privileges to install packages and write system files." >&2
    exit 1
  fi
  SUDO="sudo"
fi

function prompt_var() {
  local key="$1"
  local prompt="$2"
  local default_value="${3-}"
  local value

  if [[ -n "$default_value" ]]; then
    read -rp "$prompt [$default_value]: " value
    value="${value:-$default_value}"
  else
    read -rp "$prompt: " value
  fi
  echo "$key=$value" >>"$ENV_FILE"
}

function install_packages() {
  echo "Installing Node.js, npm, git, and Apache (httpd) via dnf..."
  $SUDO dnf install -y nodejs npm git httpd >/dev/null
}

function setup_env_file() {
  echo "\nCreating environment file at $ENV_FILE"
  : >"$ENV_FILE"
  echo "# Generated by install.sh on $(date -Iseconds)" >>"$ENV_FILE"
  echo "# Update values and restart the service if needed." >>"$ENV_FILE"

  prompt_var PORT "Port for the Node.js server" "3000"
  echo "\n# Synergy SFTP" >>"$ENV_FILE"
  prompt_var SYNERGY_SFTP_HOST "Synergy SFTP host"
  prompt_var SYNERGY_SFTP_PORT "Synergy SFTP port" "22"
  prompt_var SYNERGY_SFTP_USER "Synergy SFTP username"
  prompt_var SYNERGY_SFTP_PASSWORD "Synergy SFTP password"

  echo "\n# Synergy API" >>"$ENV_FILE"
  prompt_var SYNERGY_API_URL "Synergy API base URL"
  prompt_var SYNERGY_API_TOKEN "Synergy API token"

  echo "\n# Twilio" >>"$ENV_FILE"
  prompt_var TWILIO_ACCOUNT_SID "Twilio Account SID"
  prompt_var TWILIO_AUTH_TOKEN "Twilio Auth Token"
  prompt_var TWILIO_FROM_NUMBER "Twilio sender (From) number"
  prompt_var TWILIO_WEBHOOK_SECRET "Twilio webhook secret"

  echo "\n# SMTP2GO" >>"$ENV_FILE"
  prompt_var SMTP2GO_USERNAME "SMTP2GO username"
  prompt_var SMTP2GO_PASSWORD "SMTP2GO password"
  prompt_var SMTP2GO_API_TOKEN "SMTP2GO API token"
  prompt_var SMTP2GO_WEBHOOK_SECRET "SMTP2GO webhook secret"

  echo "\n# Entra ID" >>"$ENV_FILE"
  prompt_var ENTRA_TENANT_ID "Entra tenant ID"
  prompt_var ENTRA_CLIENT_ID "Entra client ID"
  prompt_var ENTRA_CLIENT_SECRET "Entra client secret"
}

function setup_node_dependencies() {
  echo "\nInstalling npm dependencies in $SCRIPT_DIR..."
  (cd "$SCRIPT_DIR" && npm install >/dev/null)
}

function setup_systemd_service() {
  echo "\nCreating systemd service at $SERVICE_FILE"
  cat <<SERVICE | $SUDO tee "$SERVICE_FILE" >/dev/null
[Unit]
Description=SchoolWire notification app
After=network.target

[Service]
Type=simple
EnvironmentFile=$ENV_FILE
WorkingDirectory=$SCRIPT_DIR
ExecStart=/usr/bin/node src/app.js
Restart=on-failure
User=$RUN_USER
Group=$RUN_GROUP

[Install]
WantedBy=multi-user.target
SERVICE

  echo "Reloading systemd and enabling service..."
  $SUDO systemctl daemon-reload
  $SUDO systemctl enable --now schoolwire.service
}

function setup_apache() {
  local fqdn
  local port
  port=$(grep '^PORT=' "$ENV_FILE" | cut -d'=' -f2)

  echo "\nEnter the public FQDN for Apache (e.g., schoolwire.example.org)"
  read -rp "FQDN: " fqdn
  if [[ -z "$fqdn" ]]; then
    echo "FQDN is required for Apache configuration." >&2
    exit 1
  fi

  echo "Writing Apache virtual host to $APACHE_CONF"
  cat <<APACHE | $SUDO tee "$APACHE_CONF" >/dev/null
<VirtualHost *:80>
  ServerName $fqdn
  ProxyPreserveHost On
  ProxyPass / http://127.0.0.1:$port/
  ProxyPassReverse / http://127.0.0.1:$port/
  ErrorLog /var/log/httpd/schoolwire_error.log
  CustomLog /var/log/httpd/schoolwire_access.log combined
</VirtualHost>
APACHE

  echo "Ensuring SELinux allows Apache proxying..."
  if command -v setsebool >/dev/null 2>&1; then
    $SUDO setsebool -P httpd_can_network_connect 1
  fi

  echo "Enabling and reloading Apache httpd..."
  $SUDO systemctl enable --now httpd
  $SUDO systemctl reload httpd

  if command -v firewall-cmd >/dev/null 2>&1; then
    echo "Opening HTTP service in firewalld (if running)..."
    $SUDO firewall-cmd --add-service=http --permanent >/dev/null 2>&1 || true
    $SUDO firewall-cmd --reload >/dev/null 2>&1 || true
  fi
}

function summarize() {
  echo "\nInstallation complete. Summary:"
  echo "- Environment file: $ENV_FILE"
  echo "- systemd service: $SERVICE_FILE (enabled)"
  echo "- Apache vhost: $APACHE_CONF"
  echo "Check service status with: sudo systemctl status schoolwire.service"
}

install_packages
setup_env_file
setup_node_dependencies
setup_systemd_service
setup_apache
summarize
